### ISSUE TITLE
Rendering VTK 8 compatibility

### ISSUE THREAD

**Issue by JSHBaxter** [VASST/RobartsVTK#2]
Rendering (UJ+IM) looks like it needs an overhaul for VTK 8 compatibility
   - vtkFrameBufferObject no longer exists

**Comment by JSHBaxter** [comment]
Update: Adam's been working on VTK 8 compatibility
- typedef'd FrameBuffer to be VTK7/8 agnostic (uses vtkOpenGLFramebufferObject for VTK8)
- some functions (i.e. SetNumberOfRenderTargets) are not in vtkOpenGLFramebufferObject

**Comment by adamrankin** [comment]
Yes, I started fixing this up. I will need @ujayarat help because the new vtkFrameBufferObjectBase does not the functionality that is expected. I have started to update the code to use vtkOpenGLFrameBufferObject

**Comment by adamrankin** [comment]
Yes, what J said.

**Comment by ujayarat** [comment]
Can we delay this upgrade for another couple of months? I don't think I will have time to invest on this now.

**Comment by adamrankin** [comment]
Yup

**Comment by ujayarat** [comment]
Thanks.
