### ISSUE TITLE
HMF VTK compatibility

### ISSUE THREAD

**Issue by JSHBaxter** [VASST/RobartsVTK#3]
Restructure HMF's inputs to be friendly to new VTK versions
   - remove need to call Update on input filters prior to running HMF

**Comment by JSHBaxter** [comment]
Move to testing phase

**Comment by adamrankin** [comment]
Yay!!

**Comment by JSHBaxter** [comment]
Sanity checks look good. Works (i.e. pipeline executes with no explicit Update() calls) for sample application for both GPU and CPU.
